### ISSUE TITLE
After the recent update resourcepacks are not behaving as expected

### ISSUE THREAD

**Issue by FaMa91** [Phoenix616/InventoryGui#49]
### What is happening?

This is the GUI in 1.6.1: 
![immagine](https://github.com/Phoenix616/InventoryGui/assets/13115141/ec210cc3-f31e-4de2-b63b-2710c9476b95)

This is the GUI in 1.6.2: 
![immagine](https://github.com/Phoenix616/InventoryGui/assets/13115141/c7e1a764-7fcc-4399-881a-46624bde9e35)

### What did you expect to happen?

The resourcePack's elements being showed as before or an option to choose the visualization mode if that was an intended behaviour

### Version

1.6.2

### Config

```YAML
-
```

### Server/system Version

Paper 1.19.4

### Log

```shell
-
```

### What other programs/plugins are you running?

-

**Comment by Phoenix616** [comment]
This is unlikely to have anything to do with the library. The server can't really modify client-side behaviour like that. Your post also doesn't include any info regarding how you are actually displaying it. It might be due to how you are doing that so please provide that too (but seeing as this isn't really a feature provided bj InventoryGui itself I can't guarantee that I can help you there. I only have limited experience with texturing GUIs)

Also neither "1.6.1" nor "1.6.2" are versions offered by this library, there are (right now) only snapshots so please specify which exact snapshot date/build number you are testing this with.

**Comment by FaMa91** [comment]
I was talking about 1.6.1-SNAPSHOT and 1.6.2-SNAPSHOT

Anyway it wasn't your plugin, it was my collaborator who changed the texture.
Sorry :P
